# Generated by Django 5.0.4 on 2024-04-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0003_alter_player_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='top_5_scores',
            field=models.JSONField(blank=True, default=list, verbose_name='Best five resoults'),
        ),
    ]
