# Generated by Django 5.0.4 on 2024-04-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0004_alter_player_top_5_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='success_games',
            field=models.PositiveIntegerField(default=0, verbose_name='Success games'),
        ),
    ]
