# Generated by Django 5.0.4 on 2024-04-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0006_alter_player_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='success_games',
            field=models.FloatField(default=0, verbose_name='Success games'),
        ),
    ]
