# Generated by Django 5.0.4 on 2024-04-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0007_alter_player_success_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='success_games',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Success games'),
        ),
    ]
