# Generated by Django 5.0.4 on 2024-04-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0009_alter_player_averange_resoult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='averange_resoult',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Averange game time'),
        ),
    ]
